---
apiVersion: v1
kind: Secret
metadata:
    name: sn-secret
    namespace: apps
    labels:
        group: standardnotes
type: Opaque
# Requried ENV
#   DB_PASSWORD:
#   AUTH_JWT_SECRET:
#   JWT_SECRET:
#   LEGACY_JWT_SECRET:
#   PSEUDO_KEY_PARAMS_KEY:
#   ENCRYPTION_SERVER_KEY:
#   REDIS_URL:
#   SECRET_KEY_BASE:
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:9meJcXt17Y0wvl4s1iqeTAHvfAKmLt87IgQ=,iv:RQ/PHB9URXs5JagMna7RUqO4cxMpFdaGE8ntNIFElgc=,tag:p1nVbwP7D3MpkMoB7YD+dQ==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:gdNq2RBkr/PI0eNIyC2xa3EeN6EK4E7DddxO0ef3Ras=,iv:tcBAM0fljLmON0spUQweOaWqKqVduPJLGqOeEQ5reVM=,tag:i6KZ/5o+kjwE3XvB3V3H7w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:+EDcyG8Xft0WXX6urnvD/7toTXro+jXpF8pyOoXJd/0=,iv:mMrVrtKW2up1RBKFBs4LnJcX2Q/yWqfA/iuDiJ4UdBo=,tag:bF32Axp6B6PEzeX1R3ddjg==,type:str]   
    LEGACY_JWT_SECRET: ENC[AES256_GCM,data:P2Zkk0v9AjkXpc/5XFXz8xCDoMhBHA2ePaieFUppY5Y=,iv:GIu756zQu5vTU4NhR0m5GlHBGNELSSwc3y49TlJg+qE=,tag:8nMNgtxA486/QAjkUN89ag==,type:str]
    PSEUDO_KEY_PARAMS_KEY: ENC[AES256_GCM,data:1E956Ch66GNpFRKQirZ8mWOOqS6fsYcDNRNJTCoXr7w=,iv:MJVzHtT8h70jL49GuSg0rJFUutd0OJh+g7hw670hZxw=,tag:OZz0IRGxnxtVscIf4kvAQQ==,type:str]
    ENCRYPTION_SERVER_KEY: ENC[AES256_GCM,data:Cz6eFed3hS7h23+AxX9VVIxVZtU//A/Cl56HRacesme2I4bKL2fn0I8i1o06YmpHrP0F+U7RQs5SFZQUM9l+vw==,iv:bveg9N9ImH+xb2Tp7Ql/BvYXKOaRH38Og4rJfpCI63g=,tag:e0hmyPZ0eTTTZ9pVBXBIWA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:JUd7LZkdfhMgw9sHyAz8W/EX/IzEAcKhqcKQgPYLV6EKSMHnA4l4ajSA0r5KOJQcFhLfEOUI+ZDkyyFqIzLdk0FhogqRnJlHLU7BR0hoVQ==,iv:fgCyWblMywuVws2jkZARlERMKLgrOApWBFrZsww8LsU=,tag:wPbSx4dkvFfqAQ3yPhaNwg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:W/VFVzCg+PAuMPKN5DHReHvbb1U4yxKHqBVLxUhf9jw=,iv:wf/Sf7zBQMndLMQsm7Z3WGByopaYPn6hH7iOO5K3i/E=,tag:GvZosiszZ/tbXclQas12YA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-03T01:50:05Z"
    mac: ENC[AES256_GCM,data:rJ4CxbYluFNoUZEC14tdabzYKnfsGjleeWVGXrGcxM4WheggaynHWdbo3BJcXqbq7yf54hcEb8zNC8swDHBp5hNx+ZQZUsqMvUI2NixbID90cuSYDXFV+oGBQsbUg2J8KpfP0bqFF+H+Sbgp78HrWC+46geYCjP0zh5EaK1AClU=,iv:lt9Nl0UXPNHsGcTjoAogLt03McvLYWGTZD4brErc7Uc=,tag:fu6ARvi1eIRkY0s8nTkl9A==,type:str]
    pgp:
        - created_at: "2022-03-03T01:50:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyV9b1w7rilCARAAgQ65R4t+nux424CS3ikF1q0hxS6mz9TwmppsRO+rGeXH
            aOG20Erbebfcrldh5Kx36pC1DufathvUMJ70kxWlABN3+dcKj8IybHxmfZ+Rhxvp
            gWif4A+eO4+BhkQS3jj1v5hrMZuhAd3Io11zMNxw5jivHndMtE4I7VBs2ATuD7vZ
            34jxTcE54Lru6AcDHsI2C52eiUL655wLm5KKMR25tWMQC8NSR9fCESnRW2NQ2wvW
            jhVxudJkr3TBhMxSQXn+Zr/PEQtkiTjEZDTVEXCztXxR7gs9CQi2NPzXnXyLACJ1
            KB1xB6CbARDL359Pw8TPywftvexWe1uTLBOd+6+93qkoJ1Sf5Okz9NIwvG9kmaYU
            zaxfMxNnrplahnof7oChzwgiUPhkymTo/ygybF0MvYtU1F7HuvtKblRV1dNwZpMi
            /0VtUGbLweftcwkAOgaivjyfP+c/60+WQqPPdkJyHIj5l3duRUtkBalQPyPwzOUk
            T/S803yDXq8ietKDj15fUMp44NkXNOk20gBD1O9y9QcYb5L1oYWR+wqbmbjKrad8
            /RLImzx06dHXRaN15EB1xbQn8xst9EVcGhcLMggJMGmgpcyVi0sazwonP6GJRjsq
            y+TuJS4bQ7Z8/P9IDbMBikIzZSeIPL86vIMcksSUyKkQ+7TiU4XailGKaNpPEKLS
            XgGM/dLa61sGKuAdWXgWi0/K2TzJo0qpxUKO06JolRyGj8zTe4iIV+GLzMbAUkdv
            b65iJlNs5ZZIDmm4SCnr+3mo7SsGAEthl1eAcSTTpXXWCCPtrE/9eWkC0NTNWM8=
            =d/DM
            -----END PGP MESSAGE-----
          fp: 9B943C63F470C6AEF51D02E51966026E6BC4FA59
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1