apiVersion: v1
kind: Secret
metadata:
    name: step-certificates-provisioner-password
    namespace: small-steps
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:A0vEO6O4beUaozkCnDmB5xnY3XGLa6qjMsdJCJOmDv8=,iv:+TsqCjWzp029TXEZINT30yhZG6hBZw9rsAz7YST6zTk=,tag:lwX5OblDzui5CbQV5gRVeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-19T02:44:16Z"
    mac: ENC[AES256_GCM,data:kmrmgkBSGxxTknILNIP9gQPoHOzeKiWO9eh498a5upP/IwM7xeqWT2mSfxS74Dkzh4MA4FV4OKZLsDwQOjyqJMfRQHGHnLCGz4AKV/3pUEsnhDB7b/8eupRYRVZhuD0e/jf+BGu7jI40+NARRp78E7TRGHO99NH+1oMQzi222nU=,iv:+Bnkdpmbjse+ZGn6NU+ejt+dEQDnPw/9uFJ38TNrGxw=,tag:lPNhLYb+nmHjuud56GgLTw==,type:str]
    pgp:
        - created_at: "2022-05-19T02:44:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10UWgYOhpeYAQ/+M/4ewxX61R+NSEgFzGtap1QGQvGN9tzyKSjjHaHlXfSY
            claNrV6UELthL90yEpLnYygH5uXsz0BuC1qRaGK9jhAJYOTXC+fZWWQgfnuQSFgX
            VtPA28ejm8kyEYbTvubX4p1+z7bZ7aA7IZ7tthqN/tsngLiuNRwqOMapWT3LzNPn
            Cth3Q+08dbOupPL4M20gt8rHIqP+VApjbDM5j5/Lw7G5o0VgE0t6gZ4BRuBlaT1Q
            7b6z4CwiNketh/VT7E99o+IcTGjydQuc6JNA0m3mHRmc7KarQcZxj6qXAtwMCohn
            dkk2u7Jk2ROigr2ZfVE52NgT1duWs9BMagwQNICsgkikALGD6zwhyd5c1nQNlHrU
            6l355WjHgg2MjhxhS0oDOaaKfSLYvoJmZJJgWKL5hMuiyKZFTgrPOg3a+DMUuNTT
            jY3Zy4V8Ggr10ZNZrkaU0jEvFEsFpO73+ZV79xy/ESyC0oclZWXlhyFz1JGGuInQ
            cRUCae+kQj2quvbDia14FpQwwteJL4ph3wRo9cXYnmxIiulvnrY1d669PY9aale+
            PfBOE+5MG6dhL1phJo8/pZjtVxdD/I8SveQrMsncDnLeO2GSWIx9ju/AWE2k09IN
            xQu0/DuHyyqEQG9Z3RcFzAodaN3BnzWQXQkwWhmENxUCDYArwCRn6Ck0Yq0mKt/U
            ZgEJAhAJGd5gKyB1FgNbhO6wA0vFZMoDGKE4AEQ7fmpRCqo5RqLi2f1rmGPhVBeN
            lxgfFLlRD2RXWXP+mubjZelbPCnTEC7Bx7OLPT8Vd5YTDK6nyvkPTlmQRamPI6Y0
            qiqFSO4ivA==
            =EEXY
            -----END PGP MESSAGE-----
          fp: 420FED6724AD4C46AAB9BC68F76AA09BCDF99CA2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
