apiVersion: v1
kind: Secret
metadata:
    name: step-certificates-secrets
    namespace: small-steps
type: Opaque
stringData:
    intermediate_ca_key: ENC[AES256_GCM,data:eaxZkSoKiMqaDXMSdIkGkhASGf6K9opeMOMxpNoGEdkmIMG1ldBY21the5WZu8UhNfg/w1TvzW+UksIcHjbOUqHdavJXpmNiSpG8eNe5fLwtjL9RaJjICM8Jbiipozxl7edR9uBjiYw1nn9QVpw1h6gajVyWMcEzYLddWApbrCFDLv+D2uNY2r6hZcR3XI7uIur6ABUQmPMEH1YG8fRuwISI28QsVOsePfFXRv0wJpNK6Cl4xzXfdJA8YeaLWuMwaSxvY5vx0DaC7g6GbJI6cE3CUZjjAWd6iFBliCTYPfxTSATCprHGudW86CdHi3SVOm0oukx9oLghE428EkaLPKVYBh1HUFJmeBh2TYCUdrXnvRAFtM/hdmDYDcX25PKtoucn90jXYYPV8axcvg+uk2BjiRQKdl6BnLk=,iv:xZq7VKHxIggfwewvBpObZ3KVvYPClKBMp++/ncTQHpI=,tag:+r3XkFSuvAVSegpRIPHWXQ==,type:str]
    root_ca_key: ""
    certificate_issuer_key: ""
    ssh_host_ca_key: ""
    ssh_user_ca_key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-19T21:55:04Z"
    mac: ENC[AES256_GCM,data:iYPlWnad4zGeldNV+bPGeMheoVjQo4KiCQOy2s6P6cK6u1Oc+QqWwrgRUX7tPgHgjnbfffZAWRoeUclQGbaKxPyuS7VBLL21BW2HRLHKTHimCTFk0NJIU4e0NJAk6A8cJh1wtgiAQbHra6zMSx/zoPx1PL4bX5yQhuKoP7zVOS4=,iv:h9w5l6klsVww9sUIdH5XYoX9J4NXJAOvZSfBI2UFybY=,tag:8mCqAxmIQFUL0VUyCLsBmQ==,type:str]
    pgp:
        - created_at: "2022-06-19T21:55:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10UWgYOhpeYAQ/+LNGMcfAHsfDjwtpNcEd/3AkCS7DHu/0xnOQpII9iZBez
            ty42npZESupPgl1SjzIEwOfgjP8FTTdhzm4nE0sQucGp4R3qssKFpF5kBT06xnDL
            CXlL9AmzP6TEbbzbKexMUHkXTogTsFQsxF8uUQ8T7/EJgR1iGQGs5u1cXzxNwinJ
            unZMSrELZYXz+eR/xrGXunSEcIcdsZKkBaTWQKUjRPtEEddX4X1Gre7UpU2XQEyU
            ZkV9mYMMq0Q7DwVgDUjREFCz/EN6/blAmCCBgiSRDYyUjdwQvvnkc0wbKzLxuJpt
            hYDkzRnWL0FRmCDNaJE4luQV0Fm2p8+OxqeyKzb6Tn456xUqnyTiQfoGFYyyAx0l
            uL+NjXtKTzynedAT8rQQX11j4JXbNDgN88j+Dh65+24hHYVCeE4HsH0vSIKO5luk
            VNbce4Sm6aDTAibjUXazpByXXN/kl+opmJI2vTLlO/ScRTqhrRsaVLA8v/Kpt33u
            wQb4Ly+U4UAi7AO6MlMxn9tpjSxbZOtk8dUNy3hoQsk9uR+Wj99r5J0trbULkcFt
            oUfPWlYLP3hUn7oR6sEnyjMCjKoiEsNZeDuRLIVws9ejSD+gKonAT2dhN83UtLh4
            gKfOXU2vHB45j4gQJlbyFUc5HAuxakfhjwpNkdqLZSyLNDW862sGNDc1/0RlcvDS
            XgF/VhaWfn8xzrzKyTqbSIjdhflWL+tKomLl820KLVx935CkZjLt1+ovjVmXKNlM
            VwohueWSReONPDwYGLL6OhlWLktSqbls3WXayJii9WreF2FD82OOb72ghhb6qLI=
            =SvES
            -----END PGP MESSAGE-----
          fp: 420FED6724AD4C46AAB9BC68F76AA09BCDF99CA2
        - created_at: "2022-06-19T21:55:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DV/s3aZyXgOMSAQdADi8Wa1ugmaenENy0IdKlI+i5fNZnhviyympGuHD6CTow
            GA0G1igvYkZvmxMNVO9DwCOSgTT7ZW9FFdSfP4P9YmLIDNusYUyO8lnLx5uJfAa9
            0l4BCsIxdXSKMdddtQb/ZJ7uoa6NymeX+nhcYG5k9eFHZMpEnGe2f7oLUqpQ6CC2
            eIhAtAQoyknmoN89/CAfut7KbN9xZpNybU+BzAVqZKfqCvfGjY+tyrgAbyoqXEKC
            =7eIU
            -----END PGP MESSAGE-----
          fp: 71DADA7922B3E08101B3341369C476704F97DBDA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
