apiVersion: v1
kind: Secret
metadata:
    name: kured-discord
    namespace: kube-system
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:2ZXiUFWmX1ZEXAClO+iCK3u6ObexqbgdEsiF/3BbGTO+BL9YDDRfsruqtbQJm23CI2ljI8ZA6a1fyZhEQQz0ChLmwmBH87R4MUL+7Psu7b+Q5BfEOaWOEbCWlH3ymEep1ksf8Cc/CRqVHO0Q1tkNmE09aN/Iv09I,iv:zOjHD7ws1d9Wt/GYMZppxlbia3RQrqNW2zKu1nJkRvc=,tag:fKvBSJPp8nVlYUkP2fUV+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-17T14:38:12Z"
    mac: ENC[AES256_GCM,data:oM1wVBMAxVAUFIHtcmz4CMqzDzhCCwFoBRH3Mn1YslQ9RGD+1rds2TJyO1ixD3ox32OPSyf+Vnpe9tg0UZQjkq62HTBao9JIMIsYio9u1DXMljQYLlBFSE3apyt/8w6t/3mdQKbGF4jZ5TYlg6x1f7GCAt50GI0wE4AVQypyjIg=,iv:GvG3k4L6KYIfiwgnBA7nJgttMi9NsEJJ+bmNr7/j5SI=,tag:x6uFXREEHkcsYQjyhk1aUw==,type:str]
    pgp:
        - created_at: "2022-04-17T14:38:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyV9b1w7rilCARAAwmRETx+SNxKsPBRG6MaaDAaKXHyuAxHCtAXxgTWBHxZr
            b9EMOtCcsMJPW7a0A5Vdh73o+2wRRYLe7qljUoYHjiZpA71kX5sbbHeTUCcXW7Tq
            3Lf/7aLN+GWFzSY5/md0jYvMrlznRkkVKZ/n2aXT1sH/xQMmfZ5zl87VVqcSiTFp
            0jPegrKjm49GZQDXgwfHD1EH4aiajQF5FyO3VcFHPq2m/I019QhHaW+6lFPUrXAU
            2v+jgQfz9btJVpfLDnYsuyTXX99BVxlOkBHw74xHoYOZ62OhllvYtvK5itmWE2x2
            NXZYYM+2dB7fHdQX4ShLZz1odpGb/JDm28EWe6hQZaoel/qyCM7i4+57m8lkWPV4
            rtrF3IA3QyuAqI26tpFUK38Rsed9BtcO2T4ZLg88Alde2dpvtsNoHOJU+FlNjykZ
            qT6dw36mukjr0diVTP2eKn4g+tlbA/IiGveGFzoUTkSbEnVrwGUpCJkLzlsrrV/d
            qJqZgnnj1hfR+7dMgDMxM4OIm7OUL73FOvrJtynhh0ABafk+6pHBHmPrHfjRYp27
            GcmHZ1990Lamw5I+UlPRU4lGsElJvSHdeDhBHOd9ffBx2GqDaAS9zKSTYQL5UrL5
            EGo5LPfy0CjIaRTSXFiUnt0SaHHM5ZiqvFh8LalD8LfKALYOiOQzYy/Kfw6eI4vU
            ZgEJAhCsjpHJPknLlRXifQqIhd5EmxmfoSKVgqJH5xlnGWuoHVaMpZy1i7hcGjWV
            vymgnJU4wkKhqwIg5UH/rxrgeceHccVI59G52N8ASMmG7Ev8mFl4ETNC9atw0mlW
            7uOVMD4IKA==
            =1bNv
            -----END PGP MESSAGE-----
          fp: 9B943C63F470C6AEF51D02E51966026E6BC4FA59
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2