apiVersion: v1
kind: Secret
metadata:
    name: mariadb
    namespace: database
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:7Q7okYl66BPUC3R1lGui/7gDDWEC8WMFaB+n+huMff0=,iv:sPH3kwE1jUkC5sMu7xGQinRP/ohSf1ACS17s1wwg2K4=,tag:5Kh0wvWaxRNvHefwXhOTNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-13T20:56:19Z"
    mac: ENC[AES256_GCM,data:ZI8BlyKUwstnsDaQ5vPkNDyXVveIPUqbeVyPsLaDtRhL+NvbeYama0mMGWqAVyO/acxUdcykMTnmKAtHxOkD4pgX2aKPRiqWUXEtZ9i68KnTnRRuok8LznxvqFOnh5ACZCxAsORkcBIu0WP3hLAg4dqd/VtmAXuAGZl1N1y+6ns=,iv:bkeI5kRecvj5st1U31VUjpw5DKU8IlopWrO2kt32G0A=,tag:qjYGyHfbbgIqn8P84Dddog==,type:str]
    pgp:
        - created_at: "2022-06-13T20:56:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyV9b1w7rilCAQ//TKZ7vNmAkHTOX6QyqtNmMXHn/9MuafhNyvc/WT1c85Xr
            ECbK+2spWfwE8kTi42NZGLJCJD24SZGyWWaO3tcvD5+yfRMsODi42u+DjglY3j2Y
            DqnaftQ98yJjLUbLPjsLjPaX1g7Ww9IaZg4KTPuWtI88AWjzdTnXa861qrQFEJAL
            zn6ssCm27m8vb6kH8md7Q525YorVBkM5K4RM29WYBtO2+K/7UJWHWSJ1SZCZWbjE
            ES64729PGyTLwVfaTChxm4t8q6mfbv9zPdsDouZpFTAH7D4w5VzOl+pWnWl2TG1I
            ZSyDP4p3paVDMS8RdplSgwrbKcuDOpJcFFGAsHXUsccubvL7G3i1puljeifMPeGD
            w0lCq5f0eGd4nNfiTy1Cinlrh/0Gf0n7ozWHNgeTx7xedTLpCD0CDNXN+CsZmkRB
            Ve5vQLpdVmWT9wUR89OUwPEGvJNA+JMkC3dYqLUrGTucg6iVulgYfqPGlHtkR2fH
            xWiTgYnGm+UC+aiMd3d0mwtfk5GEr2ddLWxwtdMlm/ZskE9K1zji/1SMIVxDfjGI
            4UPFQjc4BAL2cpOCf30/yDcl9cCnN8ka97Hjf3Z8nz6VDHSDVt3bXQDllnD26Z/3
            FSs+XY4UCUmEIgeSCvuoRwjbXDT5ljjO8BrIYIjDQ+en2TIgQS/YyuU3I6xVRtnS
            XgHOcjwvCVHpYW+I2oIZfjKm/Wi9bM7f9J9/Wn2AIW+PVp9qE2A4IvCnFPKPOjRe
            IqCFJyt1VL9HCy8aSOBgkScqRmQ2vM/NN/s5fQva8EDxMJdyNUowFFZC910b/Ns=
            =HAnU
            -----END PGP MESSAGE-----
          fp: 9B943C63F470C6AEF51D02E51966026E6BC4FA59
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
