apiVersion: v1
kind: Secret
metadata:
    name: mariadb
    namespace: database
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:Fq9P/4LtX4KTY7kW5NdCMagnC1NVimWCpLwH+3hXmr0=,iv:fLnyKcGbP+A5g2VgpvYiR35pi3xP2rEIoZbH70bp1xE=,tag:qQ5uA/cKgd8VwpnF5A/ikQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-03T18:05:11Z"
    mac: ENC[AES256_GCM,data:0wFaoIeYNiYFuYCw1GvpPrQWLUKlAeI+PB8ho+tPLM8I9KWJ0u0HAm3fpM/aFvhAC+xQIGw8LOj6qdJJrsa+YpD2ySc+GmZ+RHMJJnH+kBYFUPzZKwQbY06PXhymNBCH/53gmLPzsrt/862VpKruSuWk39muaAnb0CNN8zwX/Ew=,iv:Zwwzg4cYDF9xxJOkIRHq9ZAL8tbtEeyl4roTBpdi6yo=,tag:B/KVnLcCPD32Y8SpcpI9wA==,type:str]
    pgp:
        - created_at: "2022-08-03T18:05:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyV9b1w7rilCARAAuAzWzDEberhdKkDg9s1idCm5GMPQan3ORhd29GvpYEcP
            aqc8wVdH2t+9hVwcbMMg8dNgQOPA75IxD0NeXvdgQF1NCQ+uUL7L7addRoqXo3NN
            ffJSntFqg9lGLzajBz79O1JFtrHB2A1zaHaJYF8Ko25HMO1ImDp+Zicj2bmbJO8D
            vxDijkgNRaIjbDM4McXVvoB36XLMpSB0XZ789DoX9Do7Ry8u50CCsnGW3uHUqb2A
            YMIDHjVDYMOfc6BXGnqGkNZRZrF4UcnU+10slVFV5kKQjBtN9/FBS3Ulw1rbOqsB
            u1CxVDxqBK+DuqJs15DctNt6uIOFIGHzYbh5eWddTSiLofh7K64Xq/bk/p9GkFDc
            k4Gt6+tE29QdXMEGYKdqXEH4aCiqLwtMWVG9TSz6C46+WoVKgxThSjKHM8UDEJ5k
            hJoV8K0MEK1gTDk0xR2oBCggfko3R4fK+ivOOeOab5Ilyfpi5eeCLyu3FmsFtESf
            fiNDqt5HYecQq+2oh9GLgNqHV51IqcQPcVLUHEoY6Ghj5ArKuzJ/IUsmMMss65sK
            nAJqb2UHv+wU1HGfg6fSKV5H4ELQkJabL+m9usM7bzEZt7taopCxCkpHSEvAiWuk
            rgddPBKCPvF3qDH6zk2bB/flj1TJ14m9y9dMQeNImnZEm9x4EYOgCdx4unFj/onS
            XgFVwcDbn+a46A9Ld004+zqh14czoMB15lB0qFSql03vtB2oplQ0U9dOZH/wR63r
            Hmr53L+qYE0miezFpHgUi4cjQ4amHWvaBRd4xJHyhbeeiGWNFcdsMIlvrrm+ZUo=
            =g3AX
            -----END PGP MESSAGE-----
          fp: 9B943C63F470C6AEF51D02E51966026E6BC4FA59
        - created_at: "2022-08-03T18:05:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DV/s3aZyXgOMSAQdAM0kmz/uCmL7svNKuT6YjX7E+ODKh8mhUZ5AvLIPY2xkw
            VmkgJWR9Y3oVcsw2wghBcICVcv2QPL5L5ePZKQzxt/pNjwVg0JKLr7DkJwBeIQ13
            0l4BK9U2VeKCuQPl9L81swxP8jrwvYEkv4fkAulAClOhHWApzaPavehP/SsNhkQ9
            A2Wp7BrcaAotWDJprKPZKeyiVw6bl6LCufX00WQfs2mp9gMRTeMubChuw/rDeKYC
            =ORff
            -----END PGP MESSAGE-----
          fp: 71DADA7922B3E08101B3341369C476704F97DBDA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
