apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 60m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 60m0s
  values:
    global:
      # Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.
      logLevel: 2
    installCRDs: true
    replicaCount: 3
    image:
      repository: quay.io/jetstack/cert-manager-controller # {"$imagepolicy": "flux-system:cert-manager-controller:name"}
      tag: v1.7.1 # {"$imagepolicy": "flux-system:cert-manager-controller:tag"}
      pullPolicy: Always
    extraArgs:
    - --dns01-recursive-nameservers-only
    - --dns01-recursive-nameservers="1.1.1.1:53"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 512Mi
    securityContext:
      runAsNonRoot: true
    podDnsConfig:
      nameservers:
      - "1.1.1.1"
      - "8.8.8.8"
    nodeSelector:
      node-role.kubernetes.io/master: "true"
    prometheus:
      enabled: false
    webhook:
      replicaCount: 3
      timeoutSeconds: 10
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 512Mi
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      image:
        repository: quay.io/jetstack/cert-manager-webhook # {"$imagepolicy": "flux-system:cert-manager-webhook:name"}
        tag: v1.7.1 # {"$imagepolicy": "flux-system:cert-manager-webhook:tag"}
        pullPolicy: Always
      serviceAccount:
        create: true
        automountServiceAccountToken: true
      securePort: 10250
      serviceType: ClusterIP
    cainjector:
      enabled: true
      replicaCount: 3
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 512Mi
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      image:
        repository: quay.io/jetstack/cert-manager-cainjector # {"$imagepolicy": "flux-system:cert-manager-cainjector:name"}
        tag: v1.7.1 # {"$imagepolicy": "flux-system:cert-manager-cainjector:tag"}
        pullPolicy: Always
