---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flame-pv
  namespace: apps
  labels:
    group: flame
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - rw
    - sync
    - nfsvers=4.1
  nfs:
    server: 10.2.25.45
    path: "/mnt/nfs/flame"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flame-pvc
  namespace: apps
  labels:
    group: flame
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi