apiVersion: v1
kind: Secret
metadata:
    name: step-certificates-secrets
    namespace: small-steps
type: Opaque
stringData:
    intermediate_ca_key: ENC[AES256_GCM,data:EInCoaD5RBcpqF5lGJjr5ZhTeRoRBM25azQ0V4UWKB9Xbib5xuT4eHmb14i3bggCmGdclF8E7oMFuYRwrEdzT04VuU8UdXzXRQxu/Ak3c9J9Hd+qK2Obs1FwlB+fCnbVVsDKspZtn2EtIedjuBTiR2NGScowEw+XKrGuOF45+lsvraOhk2UXJHf1sWo1BiwS83pdBXPS9o0CPiGyKXI2zPovieq6bTRQQEl3v6HX2jR7KgUqNXJYaqfw5lC0OzFi8MIR2nPUCmxAZwOwfeHRRDhPSOV0sgTlIwLimzLhDFVnON9ALi3TCmg2zZgDkTDqtiYMJR/GZwjraYplgUfTWxblilNMNvyizozyCTZWFUgyXFPCDmPMeERG4LUejSIR+UMUZATrIjsPXT8WvVmldelA8qOqJc2uv0Q=,iv:OkVr5zLKoIrfKhU8lKcCx8ceh+MMo06UM4xbmPKdcy8=,tag:BX72NA+zW9leX2MS1hmYqg==,type:str]
    root_ca_key: ""
    certificate_issuer_key: ""
    ssh_host_ca_key: ""
    ssh_user_ca_key: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-18T01:02:02Z"
    mac: ENC[AES256_GCM,data:hT3LqC9UEtjrl9GOuniDYFHd4tBvG5RjnXhtNV9HJxAzTyLsUYhyt3WdHfWF1gMJ1tzaoPJ3U4H5p990riUcE/V2WL2fGlk4IiAara0ic30gsdofwYEAVNcwxXPFn5BuW2u4gPXz1pHn2cy9XCAT6Iq8NItAALASmFtmQhM8BdM=,iv:ncgZ2ngOgFRXHT9wzRQbkrxDToslBUJSIlH52E3Yy1I=,tag:Rz0AaIXCTpsd7QsVSLuT5Q==,type:str]
    pgp:
        - created_at: "2022-05-18T01:00:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyV9b1w7rilCAQ/+MurRIaWOifbewi6T04H5KbREQnG7aU/37wZBJ0jIVkLX
            hH5jnp5DWvIarBXbsIkdPgJ68sJ1024Pkdx168C/Od6t3F7Ar4jx7gQpzuozE2jc
            bMxlRjll/Pc3URdGsvqfVVu+FFJnT4vJSmQUyQVmVCXiBr9FkOyyXooLXk8dtdZL
            MWIVGZVEzgSBdzb6xmxK+uJTi9KwQmPhUuHGd5pylgQclbBZ/8+8vUFaDGm0ntXY
            P4F4N3ED7+7/lEnmdafRki6G6QsHZCYwc+CTaDB0EdrklixFVH/TGIBaiW6L9UaX
            huxoImLA7g3GOsqITRpRby99qz2SJPIHGp5ISTBiAGiCihAHr3nSu4XdqZIo+Tt6
            CoxOfAyuwf2Ai5g3wPDPYL21t+cm/Mvzzbut0/xpH5YyuysTwWrCPLPisk6e2OXb
            Q8qS+ozp/we5p5Q20bEtegwzBpW41uUa8gPhE51XL6vqWv/GXUh/OTdpOeljB3jR
            HQAK9NMZLnf+i6wKxQE94MhbclZMZ0se2h385tBYytPqnhROTjSPrnMYuQVrUnth
            zylhEAmbXy8l+z6knJauJzh0JHJGkdmEccmvURpEGLKUrYGybaqSem3u/Z1uw/8P
            f53Tde8DfOsY5O03qYIrXWehtE14fadwT+6BzVaKv8IyNuiX+iJ+dk88vk43+xrU
            aAEJAhDaihbFzbJegzqGoCXTWJnA+zHTTvmE5heH5w9ZjlvwuSd/DbcJS5jFzBS6
            Ajf39bRQ/qYcqYR/uR4cfdZOmi91trib9ksoE9SC5uBqHmcbatRROMkKatxKCWFC
            wyiR9urgASGv
            =T3uX
            -----END PGP MESSAGE-----
          fp: 9B943C63F470C6AEF51D02E51966026E6BC4FA59
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
