apiVersion: v1
kind: Secret
metadata:
    name: kured-discord
    namespace: kured
type: Opaque
stringData:
    url: https://discord.com/api/webhooks/949775022363389973/uRCXxQL_5WjVg6NWsAsnQ8pCfmk-5gztFJ5RB5jOtlBtaURkQi6BaAZ6CgDy3uNxKjvY
