---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adrp-xyz
  namespace: apps
spec:
  secretName: tls-cert-adrp-xyz
  privateKey:
    rotationPolicy: Always
  dnsNames:
  - adrp.xyz
  - "*.adrp.xyz"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
