---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: ingress
spec:
  selector:
    matchLabels:
      app: maria
  serviceName: "maria"
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: maria
    spec:
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: "critical.derpaholic.com"
          operator: "Equal"
          value: "mission"
      containers:
      - name: nginx
        image: mariadb:10.5
        envFrom:
        - secretRef:
            name: mariadb
        ports:
        - containerPort: 3306
          name: db
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "25m"
            memory: "32Mi"
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql 
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 5Gi
