---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql-operator
  namespace: mysql-op
spec:
  chart:
    spec:
      chart: mysql-operator
      version: 2.0.4
      sourceRef:
        kind: HelmRepository
        name: mysql-operator
        namespace: flux-system
  interval: 1m0s
  values:
    image:
      registry:
      repository: mysql
      name: mysql-operator
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""
      pullSecrets:
        enabled: false
        secretName:

    envs:
        imagesPullPolicy: IfNotPresent
        imagesDefaultRegistry:
        imagesDefaultRepository: