apiVersion: v1
kind: Secret
metadata:
    name: flame-secret
    namespace: apps
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Q0GcbU9XCnDUCgM4zhJeWA==,iv:8+I0Z7tYhMsBouefRTrtwHoSXvC4XD+rVI0Fru1R9s0=,tag:j3sADBYP5FSuBGqubVAUkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-21T20:26:24Z"
    mac: ENC[AES256_GCM,data:1J9EfjtwXtaalZ8+54siIPukusdiRK7/u6Gn7cgz99iFOvQ0dPtCpedxt2wQlIAkeQxyDwvEKxb54T7fXR73xD7WJnSjw1vTHvmwVMh4FpiBKbcLDQr9yfzma5MxXgd/pjZctlj2pgpJh1R97dVXDZt20qL2G7AKATrKiqFCyns=,iv:2qlSL2ldlL95SuKcTGM+ZFWv3QFikJUYTR2uoPD4Lp0=,tag:/pzz64wwbQy0um+I7ylhUA==,type:str]
    pgp:
        - created_at: "2022-05-21T20:26:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyV9b1w7rilCAQ/7Ba1ztnBlcFyNDXml/LCeROmPaeUZHnQuFe2cf61C/gxm
            deRZ8NqF0/PxukUshFYK95vVq4lF2M0XpIr6y62ppm/+GvgTd+WGUfBQdvWOH11Y
            C70IwGxPy+9zd3aXJ3FcnWWUB1zAxxMSRnd1kiTBrXKJiWbKMO9HzzEIhZPgbTDO
            //ronVGo1HtKaFwkySTjXweNCaZjLCByRPHKjjDP2cM0sufR3PzBlVc3Gp6cM5uW
            y3xd0IZBanqbpkALJlj4N1PcETZEEof701XdFfjhDVytvgdHV5sPzppzSEs9VE68
            EhR1IBELzsJ3BIrYLKpOzyoLntDMBgB2QhK7VZB83rZysxGq2F169G7Tb/ol7Tvi
            Svy3akVJsaUiH+MRs6oMjkSb9nOrL/TMqlg6xzF9R7bxQkan+iwvcNl5v05+tP8h
            DrVY1JzCYnf0+vo86ABEQG30ZDKpbN8eZKd4qyk8zkJPbaZ+2ZngG0s7RrC4FfDR
            XwPUS5JXlbD2YhDggtrmlsA/e4QfTVHgQVhhQ8B+lcG05Qqvu1dODKFppWjUIZNF
            bcKhR6HtIzvcH11GpJQMy1m5//DhNLx4e+QXhFpOeuamcrUeiId2KF8gXBrs7iLe
            wcOK1ypVgBjhf4NIaP01ec0JdmHlcJ/Ax/yGQiPcQc4tfEQE0a8SCxMINck8OPnU
            ZgEJAhDtZy+zJvNbhxkKkWqFVJS9thwBoti3F+CkSIp0pRd4cMAKg1q6iQLoZIQA
            cvQZZNhisRssbKcqevuKEe0TOxT5EbdsvAyCcpABweI9tVQunibFlgKzptootuRm
            k/BumHai3g==
            =yEw9
            -----END PGP MESSAGE-----
          fp: 9B943C63F470C6AEF51D02E51966026E6BC4FA59
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
