apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:4MzQoNTK0tizHTN5sbs8Y2DfJtlG9e2V31JeUolv579bEzZiiyNpDQ==,iv:jRdKUpbMrFkVg9U+uJqoMj5+REuUQHJYXm7P+rOVPIU=,tag:/UqbS4NOQZ9b+1ekWkp6Lw==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - pgp:
            - created_at: "2022-06-19T21:23:03Z"
              enc: |
                -----BEGIN PGP MESSAGE-----

                hQIMA10UWgYOhpeYAQ//bM0Af7VQKlh2RFTigouxsdd08LxdCqhAPd77ecJb2iSk
                Pp8I/Jdr06xrrnxtn+a3RhdV0Wr2zrPeX0I5FR+80ccqTa6Rv6soK7LatQ865bBq
                IUQRCI259h2VqNA/xsdQefRiQ7+iQIAY0a2aIXay2UZ5y5fg9mAZTCsyzmHxPOh3
                eGgb/jAm0yvQ38HOLF1i39cZtnKtff5hqWpEwBGhkcyGFS55UyfO0c6xcmgacnwf
                ybGScNofXCjo+lWQiVsWCiHTymjvQpnUQHwy4CRDix50eYPHLHmgo/7iA0++W6r2
                Am1oh4YmVPbHh1dzx9vTTQaf6GfGuiNF12Y0gHDsVCERelApvfMW/gnR39q93tPb
                dSNyZVkN3J24yzIDa3Cj39gs1IY3dSvNCPs7Gqo0O3nkXjZ/i7A0vn4Lx5J6qZY+
                +swzjG5VDY4/LWx5evfzdwJpa+ykEaon8+68P+uTwYZm928v8DzbuKQWytoKl3w2
                NreNXIZa+iB99cYhUOxN4SxDDmgqRb3HNscSxxFI5OY9LhlY3n0evPXnc1u3xzcA
                OgWyEyo94D/bumOAIbt+i+57sj2Z986ELXRGfhBQAJ64OZ+0nDxubx4suB7H1JJt
                cajgeegCIwJaZjYbRGXU3DCAHxVsFGS78W1KUiFXxTD1srr9wFyKDiIJXuchupzS
                XwGs1uVrQ3J7f12JduG17aO3C42x8Tywr+o4DdApEeM4D+78UKmdbDJrc2c5Mkfq
                HaiW1JTA6zum9HmbRYktNAcBB9hUuinKFpn8Rmn3MREkm+7iL8VtZykj23SKz+Sz
                =llTy
                -----END PGP MESSAGE-----
              fp: 420FED6724AD4C46AAB9BC68F76AA09BCDF99CA2
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1xqc2h0gazssmk3mchql6epwmkap7prv9nuknzprr9q2pzscprvfs995ukj
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNWx4UzkrOHdPU0ZPclBH
                bmtMaXNabHI0QXFIOUxpN1czS2hqUlhDR2tZCmN0UEJUT2FURVFEWHRMbUZMM212
                WFV6dFdnWXllOUM4RlU5WmJsR0NPNHcKLS0tIFpmbWJjNUJsZzJ3ZXdKM1hBQ3c1
                RUZQaVV6TUZIN002VE1BVUcvRTQ2VlEKdbmTck1MbDHONeUpzX1mp56YZOiPPRZ5
                LJHFhMc68KR0jCU/zeJQNmq8ekOBNEKWBSok7fpW/ZAeU6hHsKhp2a8=
                -----END AGE ENCRYPTED FILE-----
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-19T21:23:04Z"
    mac: ENC[AES256_GCM,data:ZeJBiI2XOiPBJNj5VBL8KA3FeB7CwHkIyQW7fUdiBtdLZdT6bWam2INiRHlRcI0paE8Pf6DSqnfKvhd4ko+qSRis39pIla2+NWo1d/DkCvdpqtTL6h/nLIAsjtXQeNOE5G52f4BV9cQ5mTzq5NiwA5Pg/yAoVkvMJupZ37bIHeE=,iv:6E1eZ/CUswhsaBBvo6otIk4ioyjPf0q49jvRrGHbX/Y=,tag:4CEUAytLVD1qXB5BR3aTGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
