---
# Source: home-assistant/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: ha-home-assistant
  labels:
    helm.sh/chart: home-assistant-13.0.1
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: ha
    app.kubernetes.io/version: "2022.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: ha
