apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: ingress
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:kZxcmqWwlECZotkjnPhWF8wHld8IODpN840uBjyocCUbSfq38Qym0Rku7QWCJzX0oWvMwA0uStpzxOL/eZvFNaC++SNCETJOeKDhB7HA0QmRxyFkOTE82tBNSxQLGQDDyjrpDmIQ9p3Qw5H/HyYyZt5gqDVJ07kqI15cijV2i//kaLqho+2fqBMLxN96dkMuFJeHXsftPTtWWtmGmmrhqL4tIicPqFTlfat+XKyJJxpSLVW0FghH,iv:7UJ47YDDhqWu2RoRVBP/SDk75ooHidKK8PugH1Rr7UU=,tag:kuvc28gUYRZAaVrgXhXtvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-17T20:11:17Z"
    mac: ENC[AES256_GCM,data:D7aELmeQSOyBZ5cyeJuuqULyL24I/5WncTwXkxtjwu8eouQavqVI9HWcepziucC6/guUm84w8trYDkkY9D6Ll5qu7Z9t220yPzpr4/8MjGELbrgVdtbr07ejWXnkUfw3ZiT8Jy738Qkuw9Acy93IGo/O3b6s4Z+ez7neZtJl8ng=,iv:4BEhgLzsY7N9j5XiTrqdybfjdzg3rJ5r9gNtIQ6hdiU=,tag:0Ce2rXJD+tyeltd+R/XcaQ==,type:str]
    pgp:
        - created_at: "2022-03-17T20:11:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8HJM/S6WGi8AQ//XdHZN65qGRs4ncWK4M8+oMhV+sKniYRjCSyFqRVl4OmU
            zNcUl41/S3R2MPEwzuFEgp9xKrjpyXDg46a8TLMSNhbCuWb5ANjemeGMR0AjVMfD
            Ls7Sc2KkQd7bWtjQklV/f/a6ioeOMGWqx+v34MqMLYsyGUPPEtM0E9gw4zAaYTH4
            8MZY3QP1c5Tv3qmxQDuZeN8EsZ9GH5pb0mxcqo+4AJgXRCSNE9Vf21zvrns7Y6EE
            p05jiQkz422BGMjQ/RZJEGrQq8eVU2W1uFwzKkLmfGFZQZBsdoL168svrXWRYwlM
            IMGJ7KrnFvCf4x+37DVyNeezh9YMILtE/7tpAqHU54GhfZ31Dl9c9lmbUpDfoZ4y
            FppaQg/H1AFa7SrYN4DRHGzja+26Fn4IKTAM2msaNvHFLKReqnuMd4vPmLtK07tH
            jsWooEQJr7eO8nX7kNeKqYdH+h19iWaWK2fhwCeaNtYIJDl6RZY1yTltdJwl6okS
            kyyvaMehGBvEtTaBA3Qn+X1nw2uy6U7f8hp6/oPEtxMwTkO9uw2oV90cO0Z3G8QK
            DVB7zhrvKVc/g4NhGHF6Vw5crcDn0aeQDTETUYWCT8+fBBS/Uv/r1ruPt1RHT9X8
            oei37cc9tHIdQxjV9Am+XxANr1raY36AShz5XbVAwjjXNuw/2Hi+ho6mxOk79qvU
            ZgEJAhAmvPAiCGrCM6YJDgVqcJJ1slWGVy+xMVaMOZOBsW5s2MLOxMw1iAJpLg49
            17UiDs1DFWVehITl0CAzDvtRezgTwt3vMZvxgpQ1/c9sPG+qgv54sfA0ziaSpvmR
            0dIzpJXv6A==
            =/r+F
            -----END PGP MESSAGE-----
          fp: 412ECB5B783A4731BED1F2F8986B9B5121BCBFFD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
