apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:9giU8h6NiyKGFr46Pj8sothIOXp4FtINvgW4Xk/38KVcz6/23aOVjMUPt0EtoVydI5h9pVEBnHxUZj89MRRwimKGptbgSVCnxM4Pyh8tinhrNLHUPy2hXxVwwWx67ztgR3I/SdiL4lq3+jZI03dioC7UF5TKPpDw,iv:HSuRwW7ETjGIUlDgnrnvRFND4jc9kD9doHWvipxW2A0=,tag:4fgJQrGozvBSwMtHMpN0cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-20T17:48:09Z"
    mac: ENC[AES256_GCM,data:f8CkWSUQQFjnFQenfXJk6lKQlg8KQlu2f9y8SHPKcqQCZFYrYoVHa+pyuseuwj53YfWDv7apP1h/a5A2n+h3bQISAAOKkOxJ5vvPfdVtP2raMx7SR/Y1E8RJ3tF0BcMLImP3AjoK6kmOYcJ/+gbU1tT7IOTe5YjW4phqa71Ng4M=,iv:w421/3efQVjArBxy7u77FzOTjaXvSd9sme2asyW6d/U=,tag:kFXN6P9z8Ptaa9OGBw7fNA==,type:str]
    pgp:
        - created_at: "2022-03-07T01:42:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7YWJ9fa/MY+AQ//ecWeckUjQ28dZosv20n284LIbzvoctAsLWBGHO0nQ3Cj
            DqTszHo6GqWTdTNs64gcTLcfGXx9oJeoaauHE795ecaOVia8+B86pLiXCeEw5BKq
            KSFlBcAdLo/pG2cHwez1tBHn8LgkZksNJ/Khv5u7LTl9khPYGfjeXkcTcgE9ainQ
            APa9cUZUJACHYCllyPLAW7mfuxCSlvJi29X5A0TD7byA7DyqBuU6JPzMKwEs2jgy
            GhxV6UITaHHEA5qmVMqWVXIULPNsuZmrqolgQxM3cCxHkJsc/xdZgbXkxhAxCPNT
            CaSsSeSyZ6iGjnMWXxdyPVrB0EdSUyGz+DsFd2Y1zBFUKd2Dk0kpIbQAynBdQ1G5
            0LEhCF/0N2msoXsi+TugXI9aYfErRq6qSkMV50j6dfdFmfhxYRCScbrHXBAP6TdW
            UK7o5FvSsG1C/KVfq4+KFaFEvtGPYxRRGR/zhLsT136ZakIZHGYFL09/CH0I7JDe
            8EuBsuc38GRmAs+u/Sb1dDbCgGZY/avbmQbBpdqtpC541D7OdpPS6gaDyFExElMs
            2NyfbXEvYQIhFHow3AARYWZ0JQmd4jujsHqSOQ1Py7JPdf8wGpOYKJEGvEZ/TRDD
            qX6u2cON0kq8A/Q6hWC9zri/YbGLllYg0af8yty9MoiryrY/ZtuJrhSSOvHCvVnS
            XgHPOjzmVE+hENXi36KhcF/tzpB0z2GZtvfQlqOv1Ve5NkWxeRfiS0UN/ty+4n2T
            fqewLSnuLYAu8k8Ysp4iSt8CL5rxt7KWo0ophzS886i9NHvWPtOVIRBoyU1bwv0=
            =vwbX
            -----END PGP MESSAGE-----
          fp: 5893FC939E4E25F521347FECCD0000CE76689A55
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
