apiVersion: v1
kind: Secret
metadata:
    name: tls-cert-ip
    namespace: apps
type: kubernetes.io/tls
stringData:
    tls.crt: ENC[AES256_GCM,data:Y+g0+rArbGCrS3v2wxT0N3j7VOjo6ZNlTh4lGPml+leNse4onDGMtZRGfoYcDGa4fnuNHyQDzKw+TAwhOJ5J+xdTArt5ih1qrGFk8xWE1vNXu5dbLCa2L7S0PUMvbqdQrjYZ2bLQAq9Wn+yVcw3m18wiR91cbW90/r+yh2DyrNPXydqXGG8Q0NVLogLmsi09vk7ycXcf6hS3SWgZE3tGirEhidyLVM7BZCF1ob845KQtGcZzCFC75oyJH9wlqkRhRCXO48ouVHCvB8WZlUas04RfFyxaaJQHyjPOfdpoP1DgaGFtujuyyvmPc0qJi41QnwEmW8riIKoqXN7JwOsXdloovjqjMuOIg20WSm2bj4pOMMz0bkQ9Hj0penxm3uS2mCmDY6ULH5YCsrELt4+lx0q8nn/E9zZNYlnjxhES99n6/cKofg/rL0JLMpQidfssjoR9mTTfZn488h8zk7IuxfuNfL0k5onzfMLUrp9RUQYiTFvpapv31qD2pZ/N04Y0aSc3JdV1Q/aBt1SWqkuGN1Vr3F87s0zNrWX67QyPjKPdZo5o19td/ptONIYGaa9xhR/OuTRf0+9xErNWBCoJ1j6SYrXiW/BFMh7lCxuceHPtH1uCvA2L5TMUm/pE3Pu154kpX4Q9uoU+3NGMtxvDp8Rd/LIIF5yC5CYdBcNMpIVoI+hH4RJmAl6UdEsCCo7kkv4aXxFUC/smOTWJ5kA0fSUEPbuUH8XP0YvcW/j7jC0pNG+k6KwXjHQYpDBYo+WOvfSnHotUxDCx6fba7UopTx1t3nY8Ol21O8Dfmwi/cuJM+uLv1E7Ibc6cS+zvW3x/YvgvT813HLW/r5frzScd1/1c81GqwtKfKouxh3umUGLFdf2exWC7Rg==,iv:Q/GsB1uP5fW8lbShTEeGSqIQ0tKFZljusDZ8BbUxv+g=,tag:lEHbU75UEbM6rIsSic144w==,type:str]
    tls.key: ENC[AES256_GCM,data:hJQfje2I0FhRqBryXIAALLrvLfaW+WDSP5p3RCCW/qmR8QSQDA/Zg5GIEfPuXNxE5gZQuP2SIksXIEmnzOsXywj/MYwD1WQdn4yUfwe4fs9gYyMLy2/9QEbzZrKJwPO/Y3jSko5tlRBGlU17Gr5t8Lmxy2j60LEj3dtTEwccw5jNMn0ZtDwhMKH5z2GahNjrq4ycySrGoCrpRWt+YD2QhDYYDfKglbfwppihRhiy+KzOUsbsn8TxmHlpb17YuWCg3KMod/vXgubYYjytW++IjIBhc6wGgrOHvpq5iv6oD9QPsaY=,iv:jvjRgeGYJwcyZqsaOvO0pP51QpMVFKDqljqL8B0S3M0=,tag:qqS55aNcberCNymzrPdO0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xqc2h0gazssmk3mchql6epwmkap7prv9nuknzprr9q2pzscprvfs995ukj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ2l2VFExc2VLNXVPN3J6
            Wm9LMTA4M1UrTW9keVh5OWhNMzQwdUZVOFY4CitlbnZlNkFsb0M2TUp2OTZieTg0
            a3I3VFB1dTBwbGJadFdVNE5aaXg5Z1UKLS0tIG1COHBsbFR6V0tZL2U2QmNLUGZS
            Q1Q4dmhZaUtDM0Eyc0JVejYwZW12M1kKo8rkTvdVj6HnnLPRFMKuGL8XGzv8Vm/Q
            pU8obj8s4fhlyG2SuEgi6yrC9C/6x0gVrq3TUhoOL+hZM6Zdtpw1wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-03T18:05:09Z"
    mac: ENC[AES256_GCM,data:wlX+bbLzGCVUfK1XAfoXgDqqLg/TDpnOaVekA35qxSTZFKtJyPaCpwjn0ZIjANHp7fQZk2UNw3cJiWeTFNtmtMQdunqjk6LJCLFFptl8qCuljTO/FfcCav1bYoO2TUjf0bviOWuq5LGZD3yueZOaL1RYS4SBtgHVbIy+Olsy0G4=,iv:0GHUdu9t5S5cecI1vzJ6qhC+23m3yqMfL5WSq+oFtBQ=,tag:i5gIymGPbbwLdbElbCQqLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
