---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn  
  namespace: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 1m0s
  values:
    global:
      cattle:
        systemDefaultRegistry: ""
    image:
      longhorn:
        engine:
          repository: longhornio/longhorn-engine
          tag: v1.2.4
        manager:
          repository: longhornio/longhorn-manager
          tag: v1.2.4
        ui:
          repository: longhornio/longhorn-ui
          tag: v1.2.4
        instanceManager:
          repository: longhornio/longhorn-instance-manager
          tag: v1_20220303
        shareManager:
          repository: longhornio/longhorn-share-manager
          tag: v1_20211020
        backingImageManager:
          repository: longhornio/backing-image-manager
          tag: v2_20210820
      csi:
        attacher:
          repository: longhornio/csi-attacher
          tag: v3.2.1
        provisioner:
          repository: longhornio/csi-provisioner
          tag: v2.1.2
        nodeDriverRegistrar:
          repository: longhornio/csi-node-driver-registrar
          tag: v2.3.0
        resizer:
          repository: longhornio/csi-resizer
          tag: v1.2.0
        snapshotter:
          repository: longhornio/csi-snapshotter
          tag: v3.0.3
      pullPolicy: IfNotPresent

    service:
      ui:
        type: ClusterIP
        nodePort: ""
      manager:
        type: ClusterIP
        nodePort: ""

    persistence:
      defaultClass: false
      defaultFsType: ext4
      defaultClassReplicaCount: 1
      reclaimPolicy: Delete
      recurringJobSelector:
        enable: false
        jobList: []
      backingImage:
        enable: false
        name: ~
        dataSourceType: ~
        dataSourceParameters: ~
        expectedChecksum: ~

    csi:
      kubeletRootDir: ~
      attacherReplicaCount: ~
      provisionerReplicaCount: ~
      resizerReplicaCount: ~
      snapshotterReplicaCount: ~

    defaultSettings:
      backupTarget: ~
      backupTargetCredentialSecret: ~
      allowRecurringJobWhileVolumeDetached: ~
      createDefaultDiskLabeledNodes: ~
      defaultDataPath: ~
      defaultDataLocality: ~
      replicaSoftAntiAffinity: ~
      replicaAutoBalance: ~
      storageOverProvisioningPercentage: ~
      storageMinimalAvailablePercentage: ~
      upgradeChecker: ~
      defaultReplicaCount: ~
      defaultLonghornStaticStorageClass: ~
      backupstorePollInterval: ~
      taintToleration: ~
      systemManagedComponentsNodeSelector: ~
      priorityClass: ~
      autoSalvage: ~
      autoDeletePodWhenVolumeDetachedUnexpectedly: ~
      disableSchedulingOnCordonedNode: ~
      replicaZoneSoftAntiAffinity: ~
      nodeDownPodDeletionPolicy: ~
      allowNodeDrainWithLastHealthyReplica: ~
      mkfsExt4Parameters: ~
      disableReplicaRebuild: ~
      replicaReplenishmentWaitInterval: ~
      concurrentReplicaRebuildPerNodeLimit: ~
      disableRevisionCounter: ~
      systemManagedPodsImagePullPolicy: ~
      allowVolumeCreationWithDegradedAvailability: ~
      autoCleanupSystemGeneratedSnapshot: ~
      concurrentAutomaticEngineUpgradePerNodeLimit: ~
      backingImageCleanupWaitInterval: ~
      backingImageRecoveryWaitInterval: ~
      guaranteedEngineManagerCPU: ~
      guaranteedReplicaManagerCPU: ~
    privateRegistry:
      registryUrl: ~
      registryUser: ~
      registryPasswd: ~
      registrySecret: ~

    longhornManager:
      priorityClass: ~
      tolerations: []
      ## If you want to set tolerations for Longhorn Manager DaemonSet, delete the `[]` in the line above
      ## and uncomment this example block
      # - key: "key"
      #   operator: "Equal"
      #   value: "value"
      #   effect: "NoSchedule"
      nodeSelector: {}
      ## If you want to set node selector for Longhorn Manager DaemonSet, delete the `{}` in the line above
      ## and uncomment this example block
      #  label-key1: "label-value1"
      #  label-key2: "label-value2"

    longhornDriver:
      priorityClass: ~
      tolerations: []
      ## If you want to set tolerations for Longhorn Driver Deployer Deployment, delete the `[]` in the line above
      ## and uncomment this example block
      # - key: "key"
      #   operator: "Equal"
      #   value: "value"
      #   effect: "NoSchedule"
      nodeSelector: {}
      ## If you want to set node selector for Longhorn Driver Deployer Deployment, delete the `{}` in the line above
      ## and uncomment this example block
      #  label-key1: "label-value1"
      #  label-key2: "label-value2"

    longhornUI:
      priorityClass: ~
      tolerations: []
      ## If you want to set tolerations for Longhorn UI Deployment, delete the `[]` in the line above
      ## and uncomment this example block
      # - key: "key"
      #   operator: "Equal"
      #   value: "value"
      #   effect: "NoSchedule"
      nodeSelector: {}
      ## If you want to set node selector for Longhorn UI Deployment, delete the `{}` in the line above
      ## and uncomment this example block
      #  label-key1: "label-value1"
      #  label-key2: "label-value2"

    resources: 
      limits:
       cpu: 100m
       memory: 128Mi
      requests:
       cpu: 100m
       memory: 128Mi

    ingress:
      enabled: true
      ingressClassName: traefik
      tls: true
      tlsSecret: tls-cert-derpaholic-com
      annotations:
      #  kubernetes.io/ingress.class: nginx
      #  kubernetes.io/tls-acme: true
    enablePSP: true
