apiVersion: v1
kind: Secret
metadata:
    name: ff-sync-auth-secret
    namespace: apps
type: Opaque
stringData:
    FF_SYNCSERVER_SECRET: ENC[AES256_GCM,data:XTpw9e9kIDl5a91SCS3LlhnHYJwiAlW5OyCkjZEU8BUvO2khEUfS8amv458dE1OmrKzTIo8L7ASoKJYDv93ms1LRkvQd2nJh+WkmEHdO777QGbzpttN5hWYl6kiMHNLaN0buq+ABnzr/LMYP+9IoNN5m4yWN2hYoUwOhWUmmsfw=,iv:hOIsgsc8+oi6C+GucYdqsqgl6wxgb1hJSkOAVZEMlTE=,tag:XoHYU4BSsfEdlgwGIrR8Iw==,type:str]
    FF_SYNCSERVER_SQLURI: ENC[AES256_GCM,data:Cs4c6Uqy+sJHxFUMCQ5it2U8K5VOVFdyz52PZFO3lUntq9u/cpq4+7iHzlkx5nt6tNazfnFiCbE1R8xSiYoCc4m2w2nKTS50nhYgEwz4yGR/8WI=,iv:DNdJ6HEPB004uo5RmXk3cBXIPg7kA/0bIBOnGFoM4EA=,tag:94w0ayIIiOPEytcD1/IiUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-21T03:31:13Z"
    mac: ENC[AES256_GCM,data:08oxUtck+lc6nTpgFTnwzkVTqolC9y/7naMxlyyIDHo4ScmaiY1XpcaC6Mfrf+eY1d76VJKT19X+cdiGleZ9kyJ5UKvT3x6Vs5dz3kFSDu1tP1tNpVa5yEExFZHEA04ldOmYKF9wGNWK4V2RCcsxGVps2UvAuswk7lMXT8WaIHA=,iv:rDi4M+YfgRBPFYqRAOgZaTE8CsvVJDctPuHzenynNTc=,tag:+sQvoRkMcD5bzA0mJCHwDg==,type:str]
    pgp:
        - created_at: "2022-05-21T03:31:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyV9b1w7rilCARAAsxlPM6+YUDXvRSPW6NgQuh2gt3StoE1eouV48g/+EuPS
            aHcX5gbkA37e79o3dinOXOL2oFWG/THmN+uZ19zy5z/nYWDQzJfOnPe0DwFdtC8z
            w4nsDbuPrO2UGC1eIsGL/DhD6OutKqogeEpey3tMwCXMj0+y6eWrt/4ab1ieN+U3
            yzm2FauS2FKeKLK8uZillyBTSMR+2303Z3XpXPY1C0X9Im34rECbwOYxq3R5gX07
            bFsHooGvdUaZF/CKGFUYFLztSCfxo4AZpl5m3CYrzCWZHESRnEtZg4zqTm8OU6lT
            0KABHUnUp4l9mXiabNX6vStkQmxsL1DQKt9SoxiVVmPB3bSexxUjG2jK+aoaTuJ7
            xDhiGH3Ie+2ySgCkbBQmFDQYxjtqD1Qcb0mCSYCXIg/smifMqSsB32oHP1uvxPNy
            RQbxNizPwxcrwPXptXUHT1eZb9Jra+NpJkMdHHZ+xB+C3JXMwem5GMsc2MUGcMOn
            Vy3l0QzfX+3GHuQTRUevwCO1m5a22U2Qpx25yEepP7vF8tN1NOR4FYXwvPixPUDQ
            Nn64jdmdudbCICFmmlMXJxLOE7mq4wI8OHnP3+J7BKWRzT07p8hYX1t5yQ6vy+qG
            b5VOjxico0jcfRef6yV10mItB+K1tnkCL05HuYZYEb9/VgnE2xtU2Ng5Ol0XkGPU
            aAEJAhDQMHxSu9CTlxjw6Iv37Fl6fgXy2/zSELjREZolRGIswlggTe/pTtKcbix+
            P/SMb5sK4NAKeWQD9ZG3YcNDuko4sPVD1MrJlfC/v3TeG7A393u9ob5nopLi8Tzr
            y2/B7zFvR8jQ
            =U/Fi
            -----END PGP MESSAGE-----
          fp: 9B943C63F470C6AEF51D02E51966026E6BC4FA59
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
