apiVersion: v1
kind: Secret
metadata:
    name: ff-sync-auth-secret
    namespace: apps
type: Opaque
stringData:
    FF_SYNCSERVER_SECRET: ENC[AES256_GCM,data:deNBFvp0Ozskz8dy+b3ZBUGMadX0JT5KcSw9+Q31xzbp1jbzhpSmpvTYzeVGQuO39NiMiSVB9OWvhjxtuNb1zaxMCZauxCBXPASlWwoMLFGQhHB37LT7MfF3gufZowK9glWkOVr4inHTgnMYkYZPqlrH14gubNgG5UoRqrx8WXk=,iv:VPO/fUKsFiih94AVn4gO5W4VTlaNDcLKivdAkzxQ4QU=,tag:Riab3yBkEHkhpM+4/xsVoA==,type:str]
    FF_SYNCSERVER_SQLURI: ENC[AES256_GCM,data:EuR+8vynNxn0y7MVU1TufRvWIJ8Id/P18QmS+zdqhB08HgFjVRE7HaR/pDu5RMzHVgZCwWWyJRvqTpaLI+ohtjK5c+bHD9W4gm21cSjpErjZIy0=,iv:ABcuh7qpkFQtP3lODhobVgN343zNcnQF2UUy+VLOkk8=,tag:rg4VijRhaZjH8H5mjG+50A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xqc2h0gazssmk3mchql6epwmkap7prv9nuknzprr9q2pzscprvfs995ukj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRzlqOFdTcnpYMEIwOVVK
            eHR3SnRPZFhiV0JBYWtEV1NnVGV2eDl1cjJnCkRRT1o2ZExBMGhoUmU1L0YrM25q
            bXg2U1VkUmRXcncyZ2p1TTZLUm5DZm8KLS0tIG84aVVmZExISSs4UzdJSkZiaGZ6
            L1FrelJBd2JmWTc1OWltZzhGMUFLM2cKMdVzJzdNQf9AjFBrkbrex76dvbcK2Cx7
            WyEWcA0udIZDZgfAdOGmbNgQ0kBtgR5i4GlHjDOY0KPsyDGO+j//lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-19T21:54:57Z"
    mac: ENC[AES256_GCM,data:6es31upR8BoeW3puq+ThgEpRiLJhaODicfHKRPtCetxhcz6LVMEkcdvSzFIsK/QWczP3Rfgia0R8fiOdKZHFsUn4r484DMqrAOAGFq/pnkeumscnHhQmW/UYb47VSIkKbQQu7Engd3DKZ7AYUuzOYmNtcU6+9uxJ2M3N3mJQ9Y4=,iv:q3BYI8hNSVW/oTvcyRtIiPoOHQHj6Xipi/cOeDHfH/g=,tag:3pg3auk6kovG/vp0ISAOOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
