---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-main
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi