---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chart:
    spec:
      chart: redis-ha
      version: "4.15.0"
      sourceRef:
        kind: HelmRepository
        name: dandydev
        namespace: flux-system
  interval: 1m0s
  values:
    fullnameOverride: "redis"
    redis:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 1024Mi
          cpu: 1000m
    sentinel:
      resources: 
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
    auth: false
    persistentVolume:
      size: "1Gi"
    additionalAffinities:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.io/arch"
              operator: In
              values: ["arm64"]
