---
apiVersion: v1
kind: Service
metadata:
  name: maria
  namespace: ingress
spec:
  ports:
    - protocol: TCP
      name: db
      port: 3306
      targetPort: 3306 # the port for the pod
  selector:
    app: maria