apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: ingress
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ye887NiQrVDolSf4EGLAbjB601Q5+Ysk6jLgDzmEqE0=,iv:zSa12aZYezbyNRtRAO5w1bWLJ5+y6c/j7tH4OC0NeX0=,tag:b57tqd5DbWUSuKmvcdYYUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-07T01:58:06Z"
    mac: ENC[AES256_GCM,data:WVHicj8YPs9VeHU2pnt9MsJEiNTrwsdawwgrFt+71nGeTY19JNhD3mCe3RUbg5A4BR9+HT6xVwzg7RJK9PfBhlvBxazjFe5qRUz9yCu77Rn8lWqtSRUAenCiBfgW02yZQFnZoAf2KXEXkbNAfZ2Q+sLvG/6JbRf8YLJMA0qHWZ4=,iv:OtGkamRYKm8tnekNtoQLmEbbKhdlpWrv3E3tRe46BVQ=,tag:h0u4Za4OD8iXbfaU26VVDw==,type:str]
    pgp:
        - created_at: "2022-03-07T01:58:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7YWJ9fa/MY+AQ//e/wJcnV/IgspEXNaz7jhn9DD5F6jWZ6OOyrBis1z4cou
            NoPJ+N8QQJvobTvu0Cd0TQB1D42YQA8AV7VZYq+S77zYkh2aTS/MbLedNdMow5bw
            jomoh4jJBqrCHcqCqAbGxSwd4DAIw71yLZpM7oRn2E68ZeE0F1kUo3Qp1Ybx4Nzf
            /hnLnWEIRUkG25hqcFGrOQuCbCNea4k8RU6I6MU5HEj2wbkiPFFuiRDJcQSWBO1R
            5d/6sqhV0ADE+FJH1eF0mY0rLaOa9UyaZMGsdXrN6mRgUkIHX2tMG5dgQodyvvjd
            kV02djfUgqhcrE3crmEiZEmX9GFo9BRxK5yt/2CggqeymzgwUCIm+ByXzp2fbj9V
            ar0q34Yv0aJDMxBWwmcQ7qnCYj7uNra6/4o40LMLsx3e8wcrjN7+Q0rDJod42pka
            Z9kdl2kv7N+KQ0DXG4Zzu5ObM9FBDX8JVV88qns/DcJx5AXa1cJLeh2rp6DvJM5o
            SPFkoYzGe1vlI7RbZa08fehueY8GTo6yG58Ikr0E1uUIVX8AfJ1InXjMzRe/8vtm
            g4vPpmfhuEYe6/Owzz5+qKMZYN0O05XFoJ+aWuKKdvEyqHYxXaOknyDpJ2O59dfw
            BkEYO19snOvRQ9agb8ZoHM8wpaG9QOy7DvKWehjEmAP2DHFkAJC03ysINywOr9XS
            XgFwCumDDxC+FE3I77x39KvTT1YT6ENzKyu2WGrkzCh/qAXDzhCwyzCvEtq2U/IH
            Ckt05R2KXiZa9Peg/0rt+USpILKIcumchLcgI8frEHNNiReX2dZWCn6S7o0NiAk=
            =Ib4b
            -----END PGP MESSAGE-----
          fp: 5893FC939E4E25F521347FECCD0000CE76689A55
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
