---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ingress
spec:
  ports:
    - protocol: TCP
      name: db
      port: 5432
      targetPort: 5432 # the port for the pod
  selector:
    app: postgres