---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero  
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      version: 2.29.8
      sourceRef:
        kind: HelmRepository
        name: tanzu
        namespace: flux-system
  interval: 120m0s
  values:
    image:
      repository: velero/velero
      tag: v1.8.1
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.4.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.io/arch"
              operator: In
              values: ["amd64"]
    metrics:
      enabled: false
    kubectl:
      image:
        repository: docker.io/bitnami/kubectl
        tag: 1.21.14
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        provider: aws
        bucket: velcro-d8k3gfw78s9iwofz5xfhiiidmjbc5wyr
        caCert:
        prefix:
        default:
        accessMode: ReadWrite
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: "https://s3.wasabisys.com"
      volumeSnapshotLocation:
        name: default
        provider: aws
        config: 
          region: us-east-1
    credentials:
      useSecret: true
      existingSecret: velero-secrets
    backupsEnabled: true
    snapshotsEnabled: true
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
