---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: some-app
  namespace: apps
  labels:
    group: blah
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: some-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
