---
apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
 name: step-issuer
spec:
 # The CA URL.
 url: https://step-certificates.small-steps.svc.cluster.local
 # The base64 encoded version of the CA root certificate in PEM format.
 caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkRENDQVJxZ0F3SUJBZ0lSQU5rWXQ4UzM3RFc3S0l0YnhWWnI5T1V3Q2dZSUtvWkl6ajBFQXdJd0dERVcKTUJRR0ExVUVBeE1OUkdWeWNIa2dVbTl2ZENCRFFUQWVGdzB5TURFeU16RXdNREkxTlROYUZ3MHpNREV5TXpFdwpNREkxTlROYU1CZ3hGakFVQmdOVkJBTVREVVJsY25CNUlGSnZiM1FnUTBFd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxCmhrak9QUU1CQndOQ0FBVE9Gb01FMEl0L2UzMjNQYWVPZ3JyUVpHVUdiejNBb3ZqSkJCRExBa3dsZDA1N2R1b3EKMnBwenJjTlFZbTMvS2ZGSnJHWlViZWwwUEhwSXFoNHVmRkpXbzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DQVFZdwpFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBVEFkQmdOVkhRNEVGZ1FVU0NzMmJSRHRNUHo0c2ZIaTNzVWZKTHc1Cm5WZ3dDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTG1ZTEZHbzlGVUFHUDZ3WTh2ajFRNXdSWFc2bjZ4Vi9TNlQKUkcvTHRNc1lBaUJ3enlKVDVIdCtEL0tueEhDcWhEVHhiL2tRUUw0MUl5RWNzd3JJZERGNHdBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
 # The provisioner name, kid, and a reference to the provisioner password secret.
 provisioner:
   name: admin
   kid: VzZlEBDg0HpIxUiUfOBVtd9nPQWdatvga3ZiAg3RX28
   passwordRef:
     name: step-certificates-provisioner-password
     key: password
     namespace: small-steps
