---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  chart:
    spec:
      chart: traefik
      version: 10.19.4
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 60m0s
  values:
    image:
      name: traefik # {"$imagepolicy": "flux-system:traefik:name"}
      tag: "2.6.2" # {"$imagepolicy": "flux-system:traefik:tag"}
      pullPolicy: IfNotPresent
    deployment:
      enabled: true
      kind: Deployment
      replicas: 1
      terminationGracePeriodSeconds: 60
      labels:
        app: traefik
    ingressClass:
      enabled: true
      isDefaultClass: true
    providers:
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
    logs:
      general:
        level: DEBUG
    metrics:
      # datadog:
      #   address: 127.0.0.1:8125
      # influxdb:
      #   address: localhost:8089
      #   protocol: udp
      prometheus:
        entryPoint: metrics
        # statsd:
        #   address: localhost:8125
    globalArguments:
    - "--global.checknewversion"
    ports:
      traefik:
        port: 9000
        hostPort: 9000
        expose: true
        exposedPort: 9000
        protocol: TCP
      web:
        port: 8000
        hostPort: 80
        expose: true
        exposedPort: 80
        protocol: TCP
        redirectTo: websecure
      websecure:
        port: 8443
        hostPort: 443
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: false
      metrics:
        port: 9100
        expose: false
        exposedPort: 9100
        protocol: TCP
    service:
      enabled: true
      type: LoadBalancer
      annotations:
          metallb.universe.tf/allow-shared-ip: "dns-shared-keys"
      spec:
        loadBalancerIP: "10.2.1.6"
    nodeSelector:
      node-role.kubernetes.io/master: "true"
