apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 60m0s
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  interval: 60m0s
  values:
    image:
      repository: k8s.gcr.io/metrics-server/metrics-server # {"$imagepolicy": "flux-system:metrics-server:name"}
      tag: "v0.6.1" # {"$imagepolicy": "flux-system:metrics-server:tag"}
      pullPolicy: IfNotPresent
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    rbac:
      create: true
      pspEnabled: false
    apiService:
      create: true
    replicas: 1
    defaultArgs:
    - --cert-dir=/tmp
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
