apiVersion: v1
kind: Secret
metadata:
    name: nginx-tls
    namespace: ingress
type: kubernetes.io/tls
stringData:
    tls.crt: ENC[AES256_GCM,data:gODJDb+mltM9zv1qWFfYshMNgKXKwfpMrgHtxtn39+N1aiJBbcteyrxxyTKacBL4NGFNMYkvUtqvLHEdjC4Y+rDU2OaiYxWSsD3ocoVep8Zn9ODIxzwYpaFKvsho+nEXpUQmUH5QNGLxXG/Gd9xugFxUizeF7/k56EPrBZCM5F+NpvU2U81CZcTrKdrgC6ZETeepoU4Ygy8dLzo4fyDpv7ZA2mCdTgJ+qkiEBzQkalaDXzc1WZEcAIAk/DWowR9cs+WZPjbiOIu3k7RaiQbPpldsMIhz5oGGfZqAZJeRt2aq5Fwybf9dpMyO1qe1KAH3xwyHnwzirDWVSgpUgquPm4xna4XVsHEa6FAJdQrX4L4LuESJ3p6YayUwwWxS2+YW0lGY0gJMZMeDx4t8v3ASIZbAwe0Tkj99UCyJREMtphd+Yp9JXHCcq9xTSvMXgJ9TdWtR+ZegZv1VIBsqZxYQXSIjgNRZHRoybuWhBd7yIHJmR0K8H9ec9NpVboQlQZx5mf1v0KcRJ5h5KtFEVYS5kRiXhJklm4sSoTNjzXCWWkhdSR2SOek4xRalyFzP7NT4ohcZG58Ut5LBqFBRqOUdstRpDWP8zIh3SemanaTjCuAtc3gHNOTXxJpDes8qPBZiJvpdzVQBz+xcl1fxrXOwxQqhDtgkpBHAKfpBeH3iNac6vrsZEdIAe/WPPSlSflx3vTMdsuaL3qjaID6lmErS/h/as+sSCIzZmHYFxwcqvZv+hzyyaUODXpH/JjN3rTWTlmMg1nw22WhsdTw3cVSmfVEvEWe/09dGHZ/P+HJDLxCIZ5tDl9stoJMT3tSz8SVsC68UL0CUP+VpDGVtgIMN,iv:12jLJSZMigh7bIetHS7uB2G0FLZGif0vONYM9mKZvIc=,tag:I5f9EiP31QR65idqYgbaHw==,type:str]
    tls.key: ENC[AES256_GCM,data:KKvuMoDD2KmZNTp0tHR8fOil7W4nXats+kVfHU1i1aA7Gw+3xshs52jo4saDwoypjiUZJ0aWlEuC2O1YCHmqgmZBiOjdjy3OwguXaAEo4KBQ9J3dvL+QerfgZ6bLS6R/wy+PkDZa87Vv4woHTfDOJnXLhOyDeIMofZ8RtyXsRo170KgIzfiq9F5YcXzvqH3ONPC6Uaq0dj/yeOYcxMMRd86VQ8bLPgIuJb6ZQLi8ZhSzHZq+AciQASUZQQMKBH/C47iUsy5mtPLPlTc3/bCCYyN/tCn1e9pZFUOMlqMgJhDfTxZoft2An/UoKHSOBN1c0ke/GWwhGgsD7t5VybC/bK4BeL/sPXfDzeR2JF+uL05q19dsuiyp5YiPEv+ZKZGpNZxMHSAmOPD5Ol0Nu1/wIT+sVV4cGgpnBg==,iv:LFr7JXkDCedMa0UN/IIVUigzVMl9imWLK+9kUa3ryw8=,tag:5XTG0g4kVem1fKp3yoA5DQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xqc2h0gazssmk3mchql6epwmkap7prv9nuknzprr9q2pzscprvfs995ukj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNekt0QytqL2RGMERxQldN
            SWdTYkFSUTQxUFdBRFFOd1lYQ0dQaSs0eVQwCnQxTks0SDlwSWhKWnd0NVNBM0h4
            VS9iWVJLcU5QUngxU0NFbEpocE1mc2cKLS0tIHRJNE1Lazk0N0J0SXVvRjNOSWgz
            TkREYmh0U2RVNkNHclhwSkRlbUFKcFUKQmEEtTvJTOv0ZZl8vJv0EQFDV52vYxSn
            cibcCBgeLhXf78zdIFXj3E+ja94mJ94tf5l/bh/TOFCq8/YNQHmujQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-19T21:55:06Z"
    mac: ENC[AES256_GCM,data:B0SNsYe3KoSxJNgMwyktsj4lf8ZbSMHA4QbwH7e97EZ4mmJXRzdMj57fCD0W+8OfQhEB+pfFUTcCaHD+GFjz1Tf8rMdWKNgNIsm0lsvCSCNP9DuGC+7mywDa1M/PDoJeON05vQE4sOO4MvcSpEESNw00SZ30wMuuvJtQvkWDe84=,iv:Uu2gk587cpr3KEGuaD+HMx5/bkxyRsiJCMBomB9YUOM=,tag:nTnHrfI3oHQD/u5/LjSGXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
