---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: posgres-operator 
  namespace: cnpg
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.13.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  interval: 1m0s
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      pullPolicy: IfNotPresent
      # -- Overrides the image tag whose default is the chart appVersion.
      tag: ""
#    imagePullSecrets: []
#    nameOverride: ""
    fullnameOverride: "posgres-operator"
#
#    webhook:
#      port: 9443
#      mutating:
#        create: true
#        failurePolicy: Fail
#      validating:
#        create: true
#        failurePolicy: Fail
#
#    # Operator configuration
#    config:
#      # -- Specifies whether the secret should be created
#      create: true
#      # -- Specifies whether it should be stored in a secret, instead of a configmap
#      secret: false
#      # Examples:
#      # INHERITED_ANNOTATIONS: categories
#      # INHERITED_LABELS: environment, workload, app
#
#      data: {}
#      name: cnpg-controller-manager-config
#
#    additionalArgs: []
#
#    serviceAccount:
#      create: true
#      name: ""
#
#    rbac:
#      create: true
#
#    podAnnotations: {}
#    commonAnnotations: {}
#
#    podSecurityContext:
#      runAsUser: 1001
#      # fsGroup: 2000
#
#    service:
#      type: ClusterIP
#      # -- DO NOT CHANGE THE SERVICE NAME as it is currently used to generate the certificate
#      # and can not be configured
#      name: cnpg-webhook-service
#      port: 443
#
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
#
#    nodeSelector: {}
#    tolerations: []
    affinity: {}
#    monitoringQueriesConfigMap:
#      name: cnpg-default-monitoring
#      queries: 