apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: apps
type: Opaque
data:
    WEBPASSWORD: ENC[AES256_GCM,data:yhD6d3YGxfGKTGHaxW+ACVMLwwvKpMW+,iv:R2WxF0o7EiwZK4bX5tWpGMkx+O2rWJ7Cnsq3c0xPuaA=,tag:McoOR5qdEizwh5lvFmRr7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xqc2h0gazssmk3mchql6epwmkap7prv9nuknzprr9q2pzscprvfs995ukj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTVArUEZTUGRsWThNZ2RD
            cnVnNUsyK1JIOXhvTS92ZXg5WWVuSWkwTEdnCkxJdzV0Q1lUbEFHV2xMZzFESkxl
            T09oaFFOQmprUXVXL0s3OEc3SVBvMzQKLS0tIEFtT1VTazZRQStmRmhHQjk3TGl3
            T0cvQVJWN0NoSzduUXMvamdSQm95bzQKtgfIvxoST2nSpX4W8kblE6tMaGMHLeH3
            cHDmaU+NArrLNm9/MkcllvH0YJ/p8VfoRkOg7F6ihGisCK33O58ZdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-03T18:05:09Z"
    mac: ENC[AES256_GCM,data:iktbYMJRS10g777zhnrpxmoansg3KuYRNdUeWzRTPqpjDHfnXXZ60wweP3a/2x7WMq3MWrK2hgpr/mXuetOQm7XBL9NXxwH1maTXpSfhfUaHYS9oLi+m7qvlI5mZY6/UVhNgOkf/l+e2Fv1OjB1QctrG86lA3rIUg9srFsCR1sw=,iv:Q6RIkBY3JiHIz+khUGPw7faH1BfgGPzf/3LfkLCaxwI=,tag:fAFHnpKBkLFIBPwRYlFDhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
