apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Y9ivbnj5GuDPx932CqFdwB5lBVZ/OM05kR40iH1X+EpxNpvU5ZKdvA==,iv:1WN0ZnOiZMrM6T6h11IoX2R1XvivKv9KqMN/PKYSDpc=,tag:zD5ULWmvH4tkuQdlvLmH9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-17T21:20:26Z"
    mac: ENC[AES256_GCM,data:vEfQ8rI0PdoPoiJLbUT6Yyu98FxJDYbmVYqEhCeqSQ6bghwtWrX16oR28tlTT+aFqC5vl/YmPp1+NKf3D07a+mA3j7dGfeuDVUyiOjHXeONL4Myk9Ne8G3OZbrCjQXqtAcQ2JW4+44G6qNQ55hxIM6nfq0CH5MBIoZSiNkYKSaI=,iv:Itigg+d5qefad6Co+Igbz+/ww2Y6ZR/71AEF9AR/B6w=,tag:B/jpqdtkHf+lr7Gc9Bq3Gg==,type:str]
    pgp:
        - created_at: "2022-03-17T21:20:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8HJM/S6WGi8AQ/+MzoIEhg09RIchvUS1ef4AD9PNIiyDmWk+2JzsmPUgrob
            y+9BDjuK1OuqPAVZG5GZz8fA5yz2xNIpFZ2a3pBdmjdZyQfYHvDMn/ZfD9x0ptxB
            DXqZKTerUFJBr/vmTs43xK/dghSae8mpeDxVoj8jymDhYoH/6kYyXHjqbf/AbVfl
            PmIPfw49noVYhYQQmZ2VmWNUJ/ihAaRlfo1VhXGksFYpTYtZ1Uv8kwJtMJNGD9AZ
            xPHXznqxRQfhMrvoFs4yKKY8x/6Z+8vJmr6xJHwMhM/JZuhOoksX/TclEbUI83E1
            z4iNI3EKajMaSu/jp7aTowMkk+Ez5ctjS8W9jeX3LlFjIkrahZPLkUot6jtlAsPB
            kLGhjhSMV/0uw3yR5v6F7nKHyOrJ8vQtOP+EGZUTKciUjjk4zLHdrvg16wnM+7xU
            Z964VUT0blcjkw4y0OREar3YvJXZH9YVyFmW9kR49Y4Yvx9hjfHD8eUrOTndqLGB
            7Zg6RAfj2NWA9F0gut0MaK9XphKEnrAcT5IemI3utEdgT2UX8MS2i8/CA2E4wHWv
            ea6HHtcvhYXfRVWIhqfp8X0finHLLU+NHWVdCnOJ/MJLZSimX0mlWTmlggyGBDcY
            4ianz90BTdUvbbyiKxVoYaFOJGm8gj0uhy805hFuaAkexKXgCIdZdS3g+OB4ECXU
            aAEJAhBXASdX8dEDrQ/J39jB7KuCMUP1yZzZ7roYjbxdjeE1g0T/yBX3xuXEdYCU
            BBOqQXZbrj4blshk3MLVpjl8HknZiKHK99nxpZ64rAMGPioB2Uo+FG9Ir3vruZCw
            HjgDVmzkHFIT
            =Qdm/
            -----END PGP MESSAGE-----
          fp: 412ECB5B783A4731BED1F2F8986B9B5121BCBFFD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
